substitutions:
  _NODE_VERSION: 10-jessie-slim
  _CLOUD_FUNCTION_RUNTIME: nodejs10
  _CLOUD_FUNCTION_ENTRY_POINT: calculate
  _CLOUD_FUNCTION_ENV_VARS_FILE: env-vars.yaml

steps:
  - id: Install Dependencies
    name: node:$_NODE_VERSION
    entrypoint: yarn

  - id: Build
    name: node:$_NODE_VERSION
    entrypoint: yarn
    args: ["build"]
    waitFor: ["Install Dependencies"]

  - id: Unit Test
    name: node:$_NODE_VERSION
    entrypoint: yarn
    args: ["test"]
    waitFor: ["Install Dependencies"]

  - id: Deploy
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        if [ ! -z "$TAG_NAME" ]; then
          functionName=$_CLOUD_FUNCTION_ENTRY_POINT
        elif [ "$BRANCH_NAME" != "master" ]; then
          urlFriendlyBranchName=$(echo "$BRANCH_NAME" |
            iconv -t ascii//TRANSLIT |
            sed -r s/[^a-zA-Z0-9]+/-/g |
            sed -r s/^-+\|-+$//g |
            tr A-Z a-z)
          functionName="${_CLOUD_FUNCTION_ENTRY_POINT}_$urlFriendlyBranchName"
        else
          exit 0
        fi

        gcloud functions deploy $functionName \
          --trigger-http \
          --runtime=$_CLOUD_FUNCTION_RUNTIME \
          --entry-point=$_CLOUD_FUNCTION_ENTRY_POINT \
          --update-labels=commit=$COMMIT_SHA \
          --env-vars-file=$_CLOUD_FUNCTION_ENV_VARS_FILE
