substitutions:
  _NODE_VERSION: 10-jessie-slim
  _CLOUD_FUNCTION_RUNTIME: nodejs10
  _FUNCTION_ENTRY_POINT: calculate
  _STORAGE_BUCKET_NAME: overengineered-calculator
  _SLACK_SIGNING_SECRET_PATH: secrets/slack-cloud-function/slack-signing-secret
  _CRYPTO_KEY_PATH: projects/intranel-oc/locations/global/keyRings/overengineered-calculator/cryptoKeys/slack-cloud-function

steps:
  - id: Install Dependencies
    name: node:$_NODE_VERSION
    entrypoint: yarn

  - id: Build
    name: node:$_NODE_VERSION
    entrypoint: yarn
    args: ["build"]
    waitFor: ["Install Dependencies"]

  - id: Unit Test
    name: node:$_NODE_VERSION
    entrypoint: yarn
    args: ["test"]
    waitFor: ["Install Dependencies"]

  - id: Deploy
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        if [ ! -z "$TAG_NAME" ]; then
          functionName=$_FUNCTION_ENTRY_POINT
        elif [ "$BRANCH_NAME" != "master" ]; then
          urlFriendlyBranchName=$(echo "$BRANCH_NAME" |
            iconv -t ascii//TRANSLIT |
            sed -r s/[^a-zA-Z0-9]+/-/g |
            sed -r s/^-+\|-+$//g |
            tr A-Z a-z)
          functionName="${_FUNCTION_ENTRY_POINT}_$urlFriendlyBranchName"
        else
          exit 0
        fi

        environmentVariables="STORAGE_BUCKET_NAME=$_STORAGE_BUCKET_NAME"
        environmentVariables+=",SLACK_SIGNING_SECRET_PATH=$_SLACK_SIGNING_SECRET_PATH"
        environmentVariables+=",CRYPTO_KEY_PATH=$_CRYPTO_KEY_PATH"

        gcloud functions deploy $functionName \
          --trigger-http \
          --runtime=$_CLOUD_FUNCTION_RUNTIME \
          --entry-point=$_FUNCTION_ENTRY_POINT \
          --update-labels=commit=$COMMIT_SHA \
          --set-env-vars=$environmentVariables
