substitutions:
  _NODE_VERSION: 10-jessie-slim
steps:
  - name: node:$_NODE_VERSION
    entrypoint: yarn
    args: ["install"]
  - name: node:$_NODE_VERSION
    entrypoint: yarn
    args: ["build"]
  - name: node:$_NODE_VERSION
    entrypoint: yarn
    args: ["test"]
  - name: gcr.io/cloud-builders/gcloud
    args:
      [
        "functions",
        "deploy",
        "calculate",
        "--trigger-http",
        "--runtime",
        "nodejs10",
      ]
