steps:
  - name: node:lts-stretch
    entrypoint: yarn
    args: ["install"]
  - name: node:lts-stretch
    entrypoint: yarn
    args: ["build"]
  - name: node:lts-stretch
    entrypoint: yarn
    args: ["test"]
