substitutions:
  _NODE_VERSION: 10-jessie-slim
  _FUNCTION_ENTRY_POINT: calculate

steps:
  - id: Install Dependencies
    name: node:$_NODE_VERSION
    entrypoint: yarn

  - id: Build
    name: node:$_NODE_VERSION
    entrypoint: yarn
    args: ["build"]
    waitFor: ["Install Dependencies"]

  - id: Unit Test
    name: node:$_NODE_VERSION
    entrypoint: yarn
    args: ["test"]
    waitFor: ["Install Dependencies"]

  - id: Remove Development Dependencies
    name: node:$_NODE_VERSION
    entrypoint: yarn
    args: ["--production"]

  - id: Deploy
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        urlFriendlyBranchName=$(echo "$BRANCH_NAME" |
          iconv -t ascii//TRANSLIT |
          sed -r s/[^a-zA-Z0-9]+/-/g |
          sed -r s/^-+\|-+$//g |
          tr A-Z a-z)

        functionName=$([ "$BRANCH_NAME" == "master" ] &&
          echo "$_FUNCTION_ENTRY_POINT" ||
          echo "${_FUNCTION_ENTRY_POINT}_$urlFriendlyBranchName")

        gcloud functions deploy $functionName \
          --trigger-http \
          --runtime=nodejs10 \
          --entry-point=$_FUNCTION_ENTRY_POINT
